name: dante
version: '1.4.3'
summary: A free SOCKS server
description: |
  Dante is a product developed by Inferno Nettverk A/S.
  It consists of a SOCKS server and a SOCKS client,
  implementing RFC 1928 and related standards.
  It is a flexible product that can be used to provide
  convenient and secure network connectivity.

confinement: strict
grade: stable
base: core20

parts:
  dante:
    plugin: autotools
    source: https://www.inet.no/dante/files/dante-1.4.3.tar.gz
    source-checksum: sha256/418a065fe1a4b8ace8fbf77c2da269a98f376e7115902e76cda7e741e4846a5d
    autotools-configure-parameters:
      - --disable-client
      - --without-libwrap
      - --without-bsdauth
      - --without-gssapi
      - --without-krb5
      - --without-upnp
      - --without-pam
    build-packages: [wget]
    override-pull: |
      snapcraftctl pull
      wget http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess
      autoreconf -ifv

layout:
  /var/log/sockd.log:
    bind-file: $SNAP_COMMON/var/log/sockd.log
  /etc/sockd.conf:
    bind-file: $SNAP_COMMON/etc/sockd.conf

apps:
  dante:
    command: usr/local/sbin/sockd
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
